name: Main
on: [push, pull_request]
jobs:
  test-main:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        libslirp_commit: [master, v4.6.0, v4.5.0, v4.1.0]
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t slirp4netns-tests --build-arg LIBSLIRP_COMMIT -f Dockerfile.tests .
      env:
        LIBSLIRP_COMMIT: ${{ matrix.libslirp_commit }}
    - run: docker run --rm --privileged slirp4netns-tests
  test-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: DOCKER_BUILDKIT=1 docker build -f Dockerfile.buildtests .
  test-centos7:
    runs-on: macos-latest
    env:
      LIBSECCOMP_COMMIT: v2.3.3
      LIBSLIRP_COMMIT: v4.1.0
      BENCHMARK_IPERF3_DURATION: 3
    steps:
    - uses: actions/checkout@v2
    - name: Setup CentOS 7 VM
      run: |
        vagrant up --provision --no-tty
        cat > ./run-vagrant-tests <<'EOF'
        exec vagrant ssh --no-tty -c "
          export LIBSECCOMP_COMMIT=\"${LIBSECCOMP_COMMIT}\"
          export LIBSLIRP_COMMIT=\"${LIBSLIRP_COMMIT}\"
          export BENCHMARK_IPERF3_DURATION=\"${BENCHMARK_IPERF3_DURATION}\"
          /src/build-and-test
        "
        EOF
    - name: Build and test with Debian 10's version of libseccomp
      run: sh ./run-vagrant-tests
    - name: Build and test with Ubuntu 20.04's versions of libseccomp/libslirp
      run: sh ./run-vagrant-tests
      env:
        LIBSECCOMP_COMMIT: v2.4.3
        LIBSLIRP_COMMIT: v4.1.0
    - name: Build and test with recent versions of libseccomp/libslirp
      run: sh ./run-vagrant-tests
      env:
        LIBSECCOMP_COMMIT: v2.5.0
        LIBSLIRP_COMMIT: v4.6.0
  artifact:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: DOCKER_BUILDKIT=1 docker build -o /tmp/artifact -f Dockerfile.artifact .
    - run: (cd /tmp/artifact; mv slirp4netns slirp4netns-x86_64)
    - run: (cd /tmp/artifact; sha256sum *)
    - uses: actions/upload-artifact@v1
      with:
        name: slirp4netns-x86_64
        path: /tmp/artifact/slirp4netns-x86_64
